mysite/blog/urls.py
from django.urls import path, re_path
from . import views


app_name = 'blog'

urlpatterns = [
    path('about/',views.AboutView.as_view(),name='about'),
    path('',views.PostListView.as_view(),name='post_list'),
    re_path(r'^post/(?P<pk>\d+)$',views.PostDetailView.as_view(),name='post_detail'),
    re_path(r'^post/new/$',views.CreatePostView.as_view(),name='post_new'),
    re_path(r'^post/(?P<pk>\d+)/edit/$',views.PostUpdateView.as_view(),name='post_edit'),
    re_path(r'^post/(?P<pk>\d+)/remove/$',views.PostDeleteView.as_view(),name='post_remove'),
    re_path(r'^drafts/$',views.DraftListView.as_view(),name='post_draft_list'),
    re_path(r'^post/(?P<pk>\d+)/publish/$',views.post_publish,name='post_publish'),
    re_path(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    re_path(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    re_path(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views
from blog.urls import urlpatterns as blogpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout', kwargs={'next_page': '/'})
]

mysite/blog/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    # This is going to connect the author to an authorisation user
    title = models.CharField(max_length=256)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True,null=True)

    def publish(self):
        self.published_date=timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse("blog:post_detail",kwargs={'pk':self.pk})

    def __str__(self):
        return self.title



class Comment(models.Model):
    post = models.ForeignKey('blog.Post',related_name='comments',on_delete=models.CASCADE)
    # This is going to connect each comment to an actual post
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse("post_list")

    def __str__(self):
        return self.text

mysite/blog/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):


    class Meta:
        model = Post
        fields = ('author','title', 'text',)

        widgets = {
            'title': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'}),
            # editable means we can edit it, medium-editor-textarea gives it the styling of the actual medium-editor, postcontent is our own class
        }


class CommentForm(forms.ModelForm):
        
        class Meta:
            model = Comment
            fields = ('author', 'text',)

            widgets = {
                'author': forms.TextInput(attrs={'class': 'textinputclass'}),
                'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'}),
            }



# This is how to connect specific widgets (form content) to CSS styling

mysite/blog/views.py
from django.shortcuts import render

# Create your views here.
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post, Comment
from blog.forms import PostForm, CommentForm
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import (TemplateView, ListView, 
                                    DetailView, CreateView, 
                                    UpdateView, DeleteView)

from django.http import HttpResponseRedirect
                                    


# Create your views here.
class AboutView(TemplateView):
    template_name = 'about.html'


class PostListView(ListView):
    model = Post

    def get_queryset(self):
        # This allows us to use django's ORM when dealing with just generic views
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
        # __lte stands for less than or equal to
        # The - in front of published_date states order by published date in a decending order; so the most recent comes up first or at the top of the list view


class PostDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'


class CreatePostView(LoginRequiredMixin,CreateView):
    # while we were working with function based views, we used decorators but now we are working with class based views we are using mixins.
    # We are going to inherit from both classes.
    login_url = '/login/'
    redirect_field_name = 'post_detail'
    form_class = PostForm
    model = Post


class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post


class DraftListView(LoginRequiredMixin,ListView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('created_date')


class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')




#######################################
## Functions that require a pk match ##
#######################################

@login_required
def post_publish(request,pk):
    post = get_object_or_404(Post,pk=pk)
    post.publish()
    return redirect('blog:post_detail',pk=post.pk)
    # return render(request=request, template_name="login.html", context={"login_form":form})


@login_required
def add_comment_to_post(request,pk):
    post=get_object_or_404(Post,pk=pk)
    if request.method =='POST':
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.post=post
            comment.save()
            return redirect('blog:post_detail',pk=post.pk)
    else:
        form=CommentForm()
    return render(request,'blog/comment_form.html',{'form':form})


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail',pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog:post_detail', pk=post_pk)

mysite/blog/templates/blog/about.html
{% extends "blog/base.html" %}

{% block content %}
<h1>About this company</h1>
<p>Thanks for checking it out</p>
{% endblock %}

mysite/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Medium Style Editor -->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Russo+One&display=swap" rel="stylesheet">

</head>
<body class="loader">

    <!-- NAVBAR -->
    <nav class="navbar navbar-default techfont custom-navbar">
        <div class="container">
    
    
          <ul class="nav navbar-nav">
            <li><a class='navbar-brand bigbrand' href="{% url 'blog:post_list' %}">My Tech Blog</a></li>
            <li><a href="{% url 'blog:about' %}">About</a></li>
            <li><a href="https://www.github.com">Github</a></li>
            <li><a href="https://www.linkedin.com">LinkedIn</a></li>
    
          </ul>
    
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li>
              <a href="{% url 'blog:post_new' %}" >New Post</a>
            </li>
    
            <li>
              <a href="{% url 'blog:post_draft_list' %}">Drafts</a>
            </li>
            <li>
              <a href="{% url 'logout' %}" >Log out</a>
            </li>
    
            <li>
              <a >Welcome: {{ user.username }}</a>
            </li>
              {% else %}
              <li><a class='nav navbar-right' href="{% url 'login' %}" ><span class="glyphicon glyphicon-user"></span></a></li>
            {% endif %}
    
          </ul>
        </div>
      </nav>

    <!-- CONTENT BLOCK -->
    <div class="content container">
        <div class="row">
            <div class="col-med-8">
                <div class="blog_posts">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
</body>
</html>

mysite/blog/templates/blog/comment_form.html
{% extends "blog/base.html" %}

{% block content %}
    <form class="post-form" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-default">Post Comment</button>
    </form>

    <script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

mysite/blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete  {{ object }}?</p>
        <input type="submit" class="btn btn danger" value="Confirm">
    </form>
{% endblock %}

mysite/blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}
    <h1 class="posttitle loader">{{post.title}}</h1>

    {% if post.published_date %}
        <div class="date postdate">
            {{post.published_date}}
        </div>
    {% else %}
        <a class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
    {% endif %}

    <p class="postcontent">{{post.text|safe|linebreaksbr}}</p>
    <!-- safe replaces bold, because when working with javascript medium, bold will come out with the tags -->

    {% if user.is_authenticated %}
          <a class="btn btn-primary" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
          <a class="btn btn-primary" href="{% url 'blog:post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
    {% endif %}

    <hr> 
    <!-- horizontal break -->

    <a class="btn btn-primary btn-comment" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">add comment</a>

    <div class="container">
        {% for comment in post.comments.all %}
            <br>
            {% if user.is_authenticated or comment.approved_comment %}
                {{comment.created_date}}
                {% if not comment.approved_comment %}
                    <a class="btn btn-default" href="{% url 'blog:comment_remove' pk=comment.pk %}">
                        <span class="glyphicon glyphicon-remove"></span>
                    </a>

                    <a class="btn btn-primary" href="{% url 'blog:comment_approve' pk=comment.pk %}">
                        <span class="glyphicon glyphicon-ok"></span>
                    </a>
                {% endif %}

                <p>{{comment.text|safe|linebreaks}}</p>
                <p>Posted By: {{comment.author}}</p>
            {% endif %}

        {% empty %}
            <p>No comments posted</p>
        {% endfor %}
    </div>

{% endblock %}

mysite/blog/templates/blog/post_draft_list.html
{% extends "blog/base.html" %}  

{% block content %}
    {% for post in posts %}
        <div class="post">
            <p class="date">created: {{post.created_date|date:'d-m-y'}}</p>
            <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a></h1>
            <p>{{post.text|truncatechars:200}}</p>
        </div>
    {% endfor %}
{% endblock %}

mysite/blog/templates/blog/post_form.html
{% extends "blog/base.html" %}

{% block content %}
    <h1>New Post</h1>
    <form class="post-form" method="POST"> 
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

    <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

mysite/blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="centerstage">
        {% for post in post_list %}
            <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a></h1>

            <div class="date">
                <p>published on: {{post.published_date|date:"D-M-Y"}}</p>
            </div>

            <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{post.approve_comments.count}}</a>
        {% endfor %}
    </div>

{% endblock %}